### ISSUE TITLE
Add support for pandas DataFrames as input data

### ISSUE THREAD

**Issue by SamedVossberg** [neuromodulation/py_neuromodulation#300] opened 2024-04-05 09:02 UTC
Currently only numpy arrays are accepted as input when creating nm_channel object. 
A name related error is thrown when running:

`features = stream.run(data)` 

Find Error reproduction in a jupyter notebook and sample data attached.
The Exception thrown is misleading. 

[reproduce_error.zip](https://github.com/neuromodulation/py_neuromodulation/files/14882602/reproduce_error.zip)

**Comment by toni-neurosc** [comment] 2024-04-15 10:00
Hello Samed. First of all thank you for reporting this issue and providing the code to reproduce it. I checked the error message and indeed there was a bug in there, in that it was showing the channels names of the input data twice, instead of comparing the input data channel names with the expected names, that are the ones set in nm_channels when initializing the stream.

After fixing that, now this is the content of the thrown Exception:
```
If data is passed as a DataFrame, thecolumns must match the channel names in `nm_channels`.
Data columns: [' EXG_Channel_0', ' EXG_Channel_1', ' EXG_Channel_2', ' EXG_Channel_3', ' EXG_Channel_4', ' EXG_Channel_5', ' EXG_Channel_6', ' EXG_Channel_7']
Expected: nm_channels.name: ['ch0', 'ch1', 'ch2', 'ch3', 'ch4', 'ch5', 'ch6', 'ch7'].
```

As you see, the problem is that the columns in the input dataframe have not been renamed to match the nm_channels object, or viceversa.  You have 2 lines that potentially fix this error:

```
data = data.rename(columns=dict(zip(data.columns[0:8], nm_channels.name)))
```
or
```
nm_channels = nm_define_nmchannels.set_channels(ch_names=data.keys()[0:8], ch_types=['SEEG']*8)
```
Notice that I have changed the slicing ranges from 1:9 in the original code to 0:8

After fixing that, that error wasn't thrown anymore but the resulting feature dataframe was empty. I noticed that there was a mismatch between the expected shape for numpy data (n_channels, n_timepoints) and the expected shape for a pandas.df (n_timepoints, n_channels). That should be fixed by PR  #301

**Closed** 2024-04-15 15:07 UTC
